/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomLink {
  'id' : bigint,
  'url' : string,
  'name' : string,
  'iconName' : string,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile {
  'customLinks' : Array<CustomLink>,
  'principal' : Principal,
  'username' : string,
  'vaultPasswordHash' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VaultNote {
  'id' : bigint,
  'encryptedContent' : string,
  'createdAt' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomLink' : ActorMethod<[string, string, string, string], CustomLink>,
  'addVaultNote' : ActorMethod<[string], VaultNote>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeVaultPassword' : ActorMethod<[string, string], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteCustomLink' : ActorMethod<[bigint], undefined>,
  'deleteVaultNote' : ActorMethod<[bigint], undefined>,
  'editCustomLink' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'editVaultNote' : ActorMethod<[bigint, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomLinks' : ActorMethod<[], Array<CustomLink>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVaultNotes' : ActorMethod<[], Array<VaultNote>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmail2faEnabled' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'resetVaultPassword' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleEmail2fa' : ActorMethod<[boolean], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];