/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'iconName' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const VaultNote = IDL.Record({
  'id' : IDL.Nat,
  'encryptedContent' : IDL.Text,
  'createdAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'customLinks' : IDL.Vec(CustomLink),
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'vaultPasswordHash' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CustomLink],
      [],
    ),
  'addVaultNote' : IDL.Func([IDL.Text], [VaultNote], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeVaultPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteCustomLink' : IDL.Func([IDL.Nat], [], []),
  'deleteVaultNote' : IDL.Func([IDL.Nat], [], []),
  'editCustomLink' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editVaultNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomLinks' : IDL.Func([], [IDL.Vec(CustomLink)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVaultNotes' : IDL.Func([], [IDL.Vec(VaultNote)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmail2faEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'resetVaultPassword' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleEmail2fa' : IDL.Func([IDL.Bool], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'iconName' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const VaultNote = IDL.Record({
    'id' : IDL.Nat,
    'encryptedContent' : IDL.Text,
    'createdAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'customLinks' : IDL.Vec(CustomLink),
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'vaultPasswordHash' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CustomLink],
        [],
      ),
    'addVaultNote' : IDL.Func([IDL.Text], [VaultNote], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeVaultPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteCustomLink' : IDL.Func([IDL.Nat], [], []),
    'deleteVaultNote' : IDL.Func([IDL.Nat], [], []),
    'editCustomLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editVaultNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomLinks' : IDL.Func([], [IDL.Vec(CustomLink)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVaultNotes' : IDL.Func([], [IDL.Vec(VaultNote)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmail2faEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'resetVaultPassword' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleEmail2fa' : IDL.Func([IDL.Bool], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };